/home/runner/work/ADBServer/ADBServer/n-adb/src/client/usb_linux.cpp:73:18: warning: field 'urb_in' with variable sized type 'usbdevfs_urb' not at the end of a struct or class is a GNU extension [-Wgnu-variable-sized-type-not-at-end]
   73 |     usbdevfs_urb urb_in;
      |                  ^
/home/runner/work/ADBServer/ADBServer/n-adb/src/client/usb_linux.cpp:74:18: warning: field 'urb_out' with variable sized type 'usbdevfs_urb' not at the end of a struct or class is a GNU extension [-Wgnu-variable-sized-type-not-at-end]
   74 |     usbdevfs_urb urb_out;
      |                  ^
3 warnings generated.
[100%] Linking CXX executable adb
ld.lld: error: unable to find library -lrt
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/CMakeFiles/adb.dir/build.make:610: src/adb] Error 1
make[1]: *** [CMakeFiles/Makefile2:441: src/CMakeFiles/adb.dir/all] Error 2
make: *** [Makefile:91: all] Error 2